name = "DtD"
uuid = "620a49e7-8616-4433-bb70-8bd2d50b6aa2"
authors = ["Finance Research Group", "xKDR", "Ayush Patnaik"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"

[compat]
Optim = "1"
julia = "1"
